<a href="https://colab.research.google.com/github/zacharski/ml-demo-22/blob/master/myNumpyIntro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
miles = 1820
gallons = 97
mpg = miles / gallons
print(mpg)

18.762886597938145


In [ ]:
print(mpg)

18.762886597938145


# Newer Intro to Numpy
## importing a library into Python

In [ ]:
import numpy as np
bodhi = np.array([1, 2, 3, 4])

In [ ]:
bodhi

array([1, 2, 3, 4])

In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
import numpy
arr3 = numpy.array([1, 2, 3])

In [ ]:
import numpy as deeplearninglibrary
arr4 = deeplearninglibrary.array([1, 2, 3])

## other ways of creating an array
### first a python example

In [ ]:
pArr  = [x for x in range(10)]

In [ ]:
pArr

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
pArr2d = [[x  + y * 10 for x in range(10)] for y in range(10)]
pArr2d

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
 [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
 [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
 [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
 [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
 [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
 [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
 [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
 [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]

#### In Numpy

In [ ]:
## no need to import numpy
nArr = np.arange(100)

In [ ]:
nArr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
nArr2 = nArr.reshape((10,10))

In [ ]:
nArr[3]

3

In [ ]:
nArr2[1][3]

13

In [ ]:
nArr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

## all the same stuff as Python - Why bother?

### Speed


In [ ]:
%time pyT1 = [[x + y * 1000 for x in range(1000)] for y in range(1000)]

CPU times: user 108 ms, sys: 44.4 ms, total: 153 ms
Wall time: 158 ms


In [ ]:
%time nuT1 = np.arange(1000000).reshape((1000,1000))

CPU times: user 0 ns, sys: 7.87 ms, total: 7.87 ms
Wall time: 12.2 ms


### add 1 to each element

#### first python

In [ ]:
def add1():
  for i in range(1000):
    for j in range(1000):
      pyT1[i][j] = pyT1[i][j] + 1
%time add1()

CPU times: user 142 ms, sys: 974 µs, total: 143 ms
Wall time: 144 ms


In [ ]:
%time nuT1 + 1

CPU times: user 355 µs, sys: 6.07 ms, total: 6.43 ms
Wall time: 7.34 ms


array([[      1,       2,       3, ...,     998,     999,    1000],
       [   1001,    1002,    1003, ...,    1998,    1999,    2000],
       [   2001,    2002,    2003, ...,    2998,    2999,    3000],
       ...,
       [ 997001,  997002,  997003, ...,  997998,  997999,  998000],
       [ 998001,  998002,  998003, ...,  998998,  998999,  999000],
       [ 999001,  999002,  999003, ...,  999998,  999999, 1000000]])

## Numpy Functions

In [ ]:
nuT1.mean()

499999.5

In [ ]:
nuT1.sum()

499999500000

In [ ]:
mpg

18.762886597938145